<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ClassLevel extends Model
{
    protected $fillable = [
        'slug',
        'serial_number',
        'name',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (ClassLevel $classLevel) {
            $classLevel->slug = Str::uuid()->toString();
        });
    }

    public function isMaxSerialNumber(): bool
    {
        return $this->serial_number == self::max('serial_number');
    }

    // TODO Scope
    #[Scope]
    protected function active(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }

    #[Scope]
    protected function filterByName(Builder $query, $name): Builder
    {
        return $query->where('name', $name);
    }

    #[Scope]
    protected function oneNextLevel(Builder $query, $id): Builder
    {
        $current = self::find($id);
        if (!$current) {
            // Return kosong jika tidak ditemukan
            return $query->whereRaw('1=0');
        }

        return $query->where('serial_number', $current->serial_number + 1);
    }
}
