<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ClassLevel extends Model
{
    protected $fillable = [
        'slug',
        'serial_number',
        'name',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (ClassLevel $classLevel) {
            $classLevel->slug = Str::uuid()->toString();
        });
    }
}
