<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Menu extends Model
{
    protected $fillable = [
        'slug',
        'serial_number',
        'name',
        'type',
        'main_menu',
        'visibility',
        'url',
        'icon',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'visibility' => 'array',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Menu $menu) {
            $menu->slug = Str::uuid()->toString();
        });
    }
}
