<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MessageTemplate extends Model
{
    protected $fillable = [
        'slug',
        'category',
        'recipient',
        'title',
        'message',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MessageTemplate $messageTemplate) {
            $messageTemplate->slug = Str::uuid()->toString();
        });
    }

    // TODO Scope
    #[Scope]
    protected function filterByCategory(Builder $query, $category): Builder
    {
        return $query->where('category', $category);
    }

    #[Scope]
    protected function filterByRecipient(Builder $query, $recipient): Builder
    {
        return $query->where('recipient', $recipient);
    }
}
