<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class StudentLevel extends Model
{
    use HasFactory;

    protected $fillable = [
        'slug',
        'student_id',
        'school_year_id',
        'class_level_id',
        'sub_class_level_id',
        'is_active',
        'is_graduate',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
            'is_graduate' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (StudentLevel $student) {
            $student->slug = Str::uuid()->toString();
        });
    }
}
